### ISSUE TITLE
Annotations not displaying on demo

### ISSUE THREAD

**Issue by gseabrook** [emory-lits-labs/annotator-imgselect#1]
I've been looking into your annotator plug in for some inspiration, and thought you might like to know that the demo site is not working properly. When I highlight part of the image, enter an annotation and click save, a yellow box appears on the area that I highlighted but I can't see any way of viewing my comment. If i hover over the yellow box I see a horizontal line with an arrow, but no way of viewing my comment.

I've tried both Chrome 50.0.2661.94 and Firefox 45.0.2, both on Mac OSX

Regards
Graham

**Comment by rlskoeser** [comment]
@gseabrook thanks for letting me know.  I think I did notice that at some point, but haven't had time to investigate much - but it's good to have it documented as an open issue.  

FWIW, the plugin works with [annotator-marginalia](https://github.com/emory-lits-labs/annotator-marginalia), which is how I'm using it in production on [Readux](http://readux.library.emory.edu) - feel free to create an account and try it out there, if you want to see it in action.  I'm not sure yet what about the default ui doesn't work with my image selection annotations (and when I looked at it briefly, it wasn't obvious).

Do you have another use for this plugin, or just looking at these plugins to write your own?  If the latter, maybe there are some documentation improvements we can identify to contribute back to annotator.js.

**Comment by gseabrook** [comment]
Thanks for getting back to me.

I have a requirement for annotating PDFs that I'm investigating, and I was looking into extending / adjusting your plugin to support any HTML element, instead of just images. 

I believe the problem is that annotator.js uses an internal implementation of the jQuery data method, which means the background data store used when the annotation is saved on the DOM element in drawImageHighlight is not the same as when annotation.js reads the data back in _onHighlightMouseover. 

I was able to solve the problem on the demo page by hacking annotator.js to expose its private jQuery instance and then calling that from drawImageHighlight, but its a pretty awful hack.

**Comment by rlskoeser** [comment]
Interesting...  that makes me wonder if the display error is some complication/conflict between the image highlighting and not using a proper annotator store for the demo.  This at least gives me a place to look, so thanks for that!

It would be neat to be able to annotate PDFs with annotator (I saw the [recent discussion of pdf annotation on the annotator-dev mailing list](https://lists.okfn.org/pipermail/annotator-dev/2016-May/001611.html)).  It would be interesting to see if this plugin could be adapted or extended for that!

**Comment by rlskoeser** [comment]
Fixed by #2.  Tagged and released as 0.2.3
